services:
  spiritualcenterapp:
    container_name: spiritualcenterapp
    build: .
    image: spiritualcenterapp:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge